os: linux
language: node_js
node_js:
- '12'
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: i+MmmxLmanqs2nBazOQYPJLs+p9ae0N+3fp6qYHtcpVmkEyUXEe1PDi4IadNMjNPX79BK1nXFYmt0SuUMUQDfl0N4h2VomPxjeQd9CNcoqMM/Q74SVp03oWvkVg8qerhepzwZC02LDl01XkEWW3jO8IxW/+naAy5KOAX8QC5m5gH15yRHlb9REMQz4RZtOReU3kkohSgglWRgUxL4qZqILbMEl9XPdNWk+P2WBX22Htcxn7dFUaWjAoZ0+gz9aN3TcKagOmRmPeDbOZmaR4ggn+yktpytyV4Xv9XQSzHlGHyz3w1A7u3AKPdFosaWnk4I5vExdkN0/lP9ymFKY/t/eHh2qgurxV5OT2QoURM1LL1R0wr+G7frOXeszStgYhj2BBNauisxsOZLfc2U1HwUXMNJraDg984OmWB8eyG44JFqVz9eRPXjCuU36tvakaxO9Kycxmwq6ENINa9dzt0t27R0O7XmT73PX1um8uGk8Ajf25PfGmuGvixIwHrW+KYgLAi+d6T/4VSfwabztQt32JoFACqNj2mdPsvQvnPLe+Sctshl1FvJHdtEfBetjtuezpiHaiJLP5CnCwxURgHZ378fvDVB8tXTEiXOfLxzsTuxxUUChA4+an22a31vKLLP0pwYdEEddNcY9A60kyt7v7tLOcsxmQ2n/qkT+Bq7Yo=
  app: codecon-codes
  on:
    branch: master
